apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
{{ include "gitlab.labels" . | indent 4 }}
    component: portal
spec:
  replicas: 1
  serviceName: "{{ template "gitlab.fullname" . }}"
  selector:
    matchLabels:
{{ include "gitlab.matchLabels" . | indent 6 }}
      component: portal
  template:
    metadata:
      labels:
{{ include "gitlab.matchLabels" . | indent 8 }}
        component: portal
    spec:
      containers:
      - env:
        - name: DEBUG
          value: "{{ .Values.portal.debug }}"
        ## Gitlab configuration
        ##
        - name: GITLAB_HOST
          value: "{{ template "gitlab.host" . }}"
        - name: GITLAB_PORT
          value: "{{ template "gitlab.port" . }}"
        - name: GITLAB_SSH_PORT
          value: "{{ template "gitlab.sshPort" . }}"
        - name: GITLAB_ROOT_PASSWORD
        {{- if .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: gitlab-root-password
        {{- end }}
        - name: GITLAB_RELATIVE_URL_ROOT
        - name: GITLAB_ROOT_EMAIL
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alphanumeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alphanumeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alphanumeric-string    
        ## DB configuration
        ##
        - name: DB_ADAPTER
          value: postgresql
        - name: DB_HOST
          value: "{{ template "gitlab.database.host" . }}"
        - name: DB_PORT
          value: "{{ template "gitlab.database.port" . }}"
        - name: DB_USER
          value: "{{ template "gitlab.database.username" . }}"
        - name: DB_NAME
          value: "{{ template "gitlab.database.gitlabDatabase" . }}"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: db-password
        ## Redis configuration
        ##
        - name: REDIS_HOST
          value: "{{ template "gitlab.redis.host" . }}"
        - name: REDIS_PORT
          value: "{{ template "gitlab.redis.port" . }}"
        {{- if .Values.redis.usePassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: redis-password
        {{- end }}
        ## HTTPS configuration
        ##
        - name: GITLAB_HTTPS
          value: "false"
        - name: SSL_SELF_SIGNED
          value: "false"
        ## TZ configuration
        ##
        - name: TZ
          value: Asia/Kolkata
        - name: GITLAB_TIMEZONE
          value: Kolkata  
        ## Backup configuration
        ##        
        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: "01:00"
        - name: GITLAB_EMAIL
          value: notifications@example.com
        - name: GITLAB_EMAIL_REPLY_TO
          value: noreply@example.com
        - name: GITLAB_INCOMING_EMAIL_ADDRESS
          value: reply@example.com
        ## Notify configuration
        ##
        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"
        ## SMTP configuration
        ## 
        - name: SMTP_ENABLED
          value: "false"        
        - name: SMTP_AUTHENTICATION
          value: login
        - name: SMTP_DOMAIN
          value: www.example.com
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PASS
          value: password
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_USER
          value: mailer@example.com          
        ## IMAP configuration
        ##          
        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        - name: IMAP_USER
          value: mailer@example.com
        ## OAUTH configuration
        ##
        - name: OAUTH_ENABLED
          value: "false"        
        - name: OAUTH_AUTO_SIGN_IN_WITH_PROVIDER
        - name: OAUTH_ALLOW_SSO
        - name: OAUTH_BLOCK_AUTO_CREATED_USERS
          value: "true"
        - name: OAUTH_AUTO_LINK_LDAP_USER
          value: "false"        
        - name: OAUTH_AUTO_LINK_SAML_USER
          value: "false"        
        - name: OAUTH_EXTERNAL_PROVIDERS
        ## OAUTH_CAS3 configuration
        ##
        - name: OAUTH_CAS3_LABEL
          value: cas3
        - name: OAUTH_CAS3_SERVER
        - name: OAUTH_CAS3_DISABLE_SSL_VERIFICATION
          value: "false"        
        - name: OAUTH_CAS3_LOGIN_URL
          value: /cas/login
        - name: OAUTH_CAS3_LOGOUT_URL
          value: /cas/logout
        - name: OAUTH_CAS3_VALIDATE_URL
          value: /cas/p3/serviceValidate
        ## OAUTH_GOOGLE configuration
        ##
        - name: OAUTH_GOOGLE_API_KEY
        - name: OAUTH_GOOGLE_APP_SECRET
        - name: OAUTH_GOOGLE_RESTRICT_DOMAIN
        ## OAUTH_FACEBOOK configuration
        ##    
        - name: OAUTH_FACEBOOK_API_KEY
        - name: OAUTH_FACEBOOK_APP_SECRET
        ## OAUTH_TWITTER configuration
        ##   
        - name: OAUTH_TWITTER_API_KEY
        - name: OAUTH_TWITTER_APP_SECRET
        ## OAUTH_GITHUB configuration
        ##
        - name: OAUTH_GITHUB_API_KEY
        - name: OAUTH_GITHUB_APP_SECRET
        - name: OAUTH_GITHUB_URL
        - name: OAUTH_GITHUB_VERIFY_SSL
        ## OAUTH_GITLAB configuration
        ##
        - name: OAUTH_GITLAB_API_KEY
        - name: OAUTH_GITLAB_APP_SECRET
        ## OAUTH_BITBUCKET configuration
        ##
        - name: OAUTH_BITBUCKET_API_KEY
        - name: OAUTH_BITBUCKET_APP_SECRET
        ## OAUTH_SAML configuration
        ##       
        - name: OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL
        - name: OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL
        - name: OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME
        - name: OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME
        - name: OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME
        - name: OAUTH_SAML_EXTERNAL_GROUPS
        - name: OAUTH_SAML_GROUPS_ATTRIBUTE
        - name: OAUTH_SAML_IDP_CERT_FINGERPRINT
        - name: OAUTH_SAML_IDP_SSO_TARGET_URL
        - name: OAUTH_SAML_ISSUER
        - name: OAUTH_SAML_LABEL
          value: '"Our SAML Provider"'
        - name: OAUTH_SAML_NAME_IDENTIFIER_FORMAT
          value: urn:oasis:names:tc:SAML:2.0:nameid-format:transient
        ## OAUTH_CROWD configuration
        ##  
        - name: OAUTH_CROWD_APP_NAME
        - name: OAUTH_CROWD_APP_PASSWORD
        - name: OAUTH_CROWD_SERVER_URL
        ## OAUTH_AUTH0 configuration
        ##  
        - name: OAUTH_AUTH0_CLIENT_ID
        - name: OAUTH_AUTH0_CLIENT_SECRET
        - name: OAUTH_AUTH0_DOMAIN
        ## OAUTH_AZURE configuration
        ##  
        - name: OAUTH_AZURE_API_KEY
        - name: OAUTH_AZURE_API_SECRET
        - name: OAUTH_AZURE_TENANT_ID
        image: {{ template "portal.image" .}}
        name: gitlab
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /home/git/data
          name: gitlab-data
      restartPolicy: Always
      volumes:
      - name: gitlab-data
{{ include "portal.volume" . | indent 8 }}
{{ include "portal.nodeSelector" . | indent 6 }}