appVersion: 11.4.0
description: GitLab Community Edition
home: https://about.gitlab.com
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
name: gitlab-ce
sources:
- https://hub.docker.com/r/sameersbn/gitlab/
- https://github.com/sameersbn/docker-gitlab
version: v0.1.2
