{{- if .Values.redis.useInternal -}}
{{- if and .Values.redis.persistence.enabled (not .Values.redis.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab.fullname" . }}-redis
  labels:
{{ include "gitlab.labels" . | indent 4 }}
    component: redis
  annotations:
  {{- if .Values.redis.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.redis.persistence.storageClass | quote }}
  {{- end }}
spec:
  accessModes: 
    - {{ .Values.redis.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
{{- end -}}